name: Build docker

on:
  push:
    branches:
      - 'master'
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'
      - '[0-9]+\.[0-9]+\.[0-9]+-RC[0-9]+'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: wmbusmeters/wmbusmeters
          tags: type=ref,event=tag
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}
      -
        name: Build and push not tagged release
        if: ${{ !steps.meta.outputs.tags }}
        uses: docker/build-push-action@v5
        with:
          context: docker/
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: wmbusmeters/wmbusmeters:latest
      -
        name: Build and push candidate
        if: ${{ steps.meta.outputs.tags && contains(steps.meta.outputs.tags, '-RC') }}
        uses: docker/build-push-action@v5
        with:
          context: docker/
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: wmbusmeters/wmbusmeters:candidate-${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
      -
        name: Build and push tagged release
        if: ${{ steps.meta.outputs.tags && !contains(steps.meta.outputs.tags, '-RC') }}
        uses: docker/build-push-action@v5
        with:
          context: docker/
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: wmbusmeters/wmbusmeters:release-${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}